with open(r'c:\CBP\HybridQuantumKnapsack\research_log\crossover_derivation.md', 'a', encoding='utf-8') as f:
    f.write('\n## 7. Correction: Scope of the Square Root and `log m` Factor\n\n')
    f.write('### Primary Source Findings\n')
    f.write('A cross-check against the primary source (`main.tex`) reveals a significant discrepancy:\n')
    f.write('1. The exact proof text quoted in the prompt ("costing O(sqrt(Tau_i * m * log m))" and the "Remark") is **not present** in the current `main.tex`. Instead, the current Proposition 1 proof (L400) bounds the per-call cost as exactly $O(\\sqrt{T_{\\tau_i}}\\,m)$ and the composed bound as $O(\\sqrt{T_{\\max}}\\,m\\log V_{\\max})$, entirely dropping the $\\log m$ factor.\n')
    f.write('2. However, cross-checking against Montanaro\'s actual Theorem statement (Equation 5, `main.tex` L162) correctly yields $O(\\sqrt{T}\\, d \\log d)$. Substituting $d = m$, the correct query complexity per threshold call is exactly $O(\\sqrt{T} \\cdot m \\log_2 m)$.\n')
    f.write('3. Therefore, the square root strictly covers ONLY $T$. The $m$ and $\\log m$ factors belong **outside** the square root.\n')
    f.write('4. **Conclusion:** The current notation in `main.tex` is underspecified/inaccurate as it silently drops Montanaro\'s $\\log d$ factor entirely from Proposition 1.\n\n')
    f.write('### Corrected Derivation\n')
    f.write('Restoring the missing $\\log_2 m$ factor outside the square root, the corrected formulas are:\n')
    f.write('- **Corrected Quantum Total Cost:** $C_Q \\cdot \\sqrt{T_{max}} \\cdot (m \\log_2 m) \\cdot \\log_2 V_{max}$\n')
    f.write('- **Corrected Crossover Formula:** \n')
    f.write('  $$ T_{max} \\ge (C_Q \\cdot m \\log_2 m \\cdot \\log_2 V_{max})^2 $$\n')
    f.write('  (This differs from the Step 4 formula by an additional factor of $(\\log_2 m)^2$).\n\n')
    f.write('### Corrected Numeric Thresholds ($T_{max}$)\n')
    f.write('- **m=4 (factor of $2^2 = 4$):** \n')
    f.write('  Old: $9.88 \\times 10^{12}$ $\\rightarrow$ **New:** $3.95 \\times 10^{13}$\n')
    f.write('- **m=6 (factor of $\\approx 2.585^2 \\approx 6.68$):** \n')
    f.write('  Old: $5.22 \\times 10^{13}$ $\\rightarrow$ **New:** $3.49 \\times 10^{14}$\n')
    f.write('- **m=8 (factor of $3^2 = 9$):** \n')
    f.write('  Old: $1.67 \\times 10^{14}$ $\\rightarrow$ **New:** $1.50 \\times 10^{15}$\n\n')
    f.write('### Qualitative Finding Confirmation\n')
    f.write('The qualitative finding remains exactly the same, but the situation is even worse for the quantum algorithm. The missing $\\log_2 m$ overhead pushes the already-unreachable crossover thresholds up by factors of 4 to 9. The empirical tree sizes ($T_{LP} \\le 3079$) remain 10-11 orders of magnitude too small to cross over.\n')
